name: Test GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        go-version: [1.22.5]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v -o ./output/project_1 ./...
