name: Test GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        go-version: [1.19, 1.20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...
